--While bootstrapping spring boot application reads from below file and creates mentioned table with sample data in h2 DB

DROP TABLE IF EXISTS PREMIUM_SELLERS;
DROP TABLE IF EXISTS APPROVED_CATEGORIES;

CREATE TABLE PREMIUM_SELLERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SELLER VARCHAR(250) NOT NULL,
  CONSTRAINT SELLER_UNIQUE UNIQUE (SELLER)
  );

INSERT INTO PREMIUM_SELLERS (SELLER) VALUES
  ('A'),
  ('B'),
  ('C');

CREATE TABLE APPROVED_CATEGORIES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY INTEGER(10) NOT NULL,
  CONSTRAINT CATEGORY_UNIQUE UNIQUE (CATEGORY)
  );

INSERT INTO APPROVED_CATEGORIES (CATEGORY) VALUES
  (10),
  (20),
  (30);